module.exports = {
  nametable: ' ',
  modulekey:'',
  tabletranslatevn: ' ',
  tabletranslateen: ' ',
  author: 'Truong.Nguyen',
  idtask: ' ',
  datecreate: Date.now(),
  taskdescription: ' ',
  entityfield: 1,
  modelfield: 1,
  gridfield: 1,
  modelsearchfield: 1,
  storenumber: 1,
  enumnumber: 1,
  numberkeypermission:1,
}
